steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'APP_ENV',
        '--build-arg',
        'DB_HOST',
        '--build-arg',
        'DB_PORT',
        '--build-arg',
        'DB_USERNAME',
        '--build-arg',
        'DB_PASSWORD',
        '--build-arg',
        'DB_DATABASE',
        '--build-arg',
        'DB_DEBUG',
        '--build-arg',
        'DB_SYNC',
        '--build-arg',
        'CORS_DOMAIN',
        '--build-arg',
        'SECRET_PK',
        '-t',
        'gcr.io/${PROJECT_ID}/lootbot-security-box-testing:$SHORT_SHA',
        '.',
      ]
    secretEnv:
      [
        'APP_ENV',
        'DB_HOST',
        'DB_PORT',
        'DB_USERNAME',
        'DB_PASSWORD',
        'DB_DATABASE',
        'DB_DEBUG',
        'DB_SYNC',
        'CORS_DOMAIN',
        'SECRET_PK',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/lootbot-security-box-testing:$SHORT_SHA']
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "lootbot-security-box-testing"
      - "--image"
      - "gcr.io/${PROJECT_ID}/lootbot-security-box-testing:$SHORT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "1"

timeout: 1200s

images:
  - gcr.io/${PROJECT_ID}/lootbot-security-box-testing:$SHORT_SHA
options:
  machineType: "E2_HIGHCPU_8"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_APP_ENV/versions/latest
      env: APP_ENV
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_HOST/versions/latest
      env: DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PORT/versions/latest
      env: DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_USERNAME/versions/latest
      env: DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_DATABASE/versions/latest
      env: DB_DATABASE
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_DEBUG/versions/latest
      env: DB_DEBUG
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_SYNC/versions/latest
      env: DB_SYNC
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_CORS_DOMAIN/versions/latest
      env: CORS_DOMAIN
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_SECRET_PK/versions/latest
      env: SECRET_PK
